trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git submodule update --init --recursive
  displayName: 'setup git submodules'

- script: |
    yarn --cwd external/core install
    yarn --cwd external/core run build
  displayName: 'build dependency: core'

- script: |
    yarn --cwd external/light-desk install
    yarn --cwd external/light-desk run build
  displayName: 'build dependency: light-desk'

- script: |
    yarn install
    git checkout node_modules
    yarn run build
  displayName: 'build ola-dmx'
